[package]
name = "dare_physics"
version = "0.1.0"
edition = "2024"
authors = ["Danny Le <git@dannydoes.graphics>"]

[dependencies]
bevy_ecs = { version = "0.17.3", features = ["default", "multi_threaded"] }
glam = "0.30.9"

